export const commonSkills = [
  'Python', 'JavaScript', 'TypeScript', 'React', 'Vue.js', 'Angular', 'Node.js', 'Express',
  'Django', 'Flask', 'Ruby on Rails', 'Java', 'Spring Boot', 'C#', '.NET', 'Go', 'Rust',
  'SQL', 'PostgreSQL', 'MySQL', 'MongoDB', 'GraphQL', 'Firebase', 'AWS', 'Azure', 'GCP',
  'Docker', 'Kubernetes', 'Terraform', 'CI/CD', 'Git', 'GitHub', 'Jenkins', 'Selenium',
  'HTML', 'CSS', 'Sass', 'Tailwind CSS', 'Bootstrap', 'Figma', 'Sketch', 'Adobe XD',
  'Photoshop', 'Illustrator', 'InDesign', 'Webflow', 'Notion', 'Miro', 'Figma',
  'Excel', 'PowerPoint', 'Google Sheets', 'Financial Modeling', 'Business Analysis',
  'Project Management', 'Agile', 'Scrum', 'Stakeholder Management', 'Product Management',
  'Marketing Strategy', 'SEO', 'Content Marketing', 'Social Media', 'Google Analytics',
  'Paid Advertising', 'Copywriting', 'Brand Strategy', 'Email Marketing', 'CRM',
  'Customer Success', 'Salesforce', 'Zendesk', 'UX Research', 'User Testing', 'A/B Testing',
  'Data Analysis', 'Data Visualization', 'Tableau', 'Power BI', 'R', 'MATLAB', 'SPSS',
  'Machine Learning', 'Deep Learning', 'NLP', 'Computer Vision', 'TensorFlow', 'PyTorch',
  'Statistics', 'Probability', 'Quantitative Analysis', 'Research', 'Problem Solving',
  'Leadership', 'Communication', 'Teamwork', 'Time Management', 'Adaptability',
  'Critical Thinking', 'Presentation Skills', 'Negotiation', 'Conflict Resolution',
  'Networking', 'Customer Service', 'Digital Advertising', 'Market Research',
  'Brand Development', 'Event Planning', 'Public Speaking', 'Organizational Skills',
  'Attention to Detail', 'Decision Making', 'Relationship Building', 'Mentoring',
  'Coaching', 'Innovation', 'Strategic Planning', 'Risk Management', 'Quality Assurance',
  'Compliance', 'Supply Chain', 'Logistics', 'Teaching', 'Copy Editing', 'Translation',
  'Video Editing', 'Motion Graphics', 'Animation', 'Photography', '3D Modelling',
  'Cybersecurity', 'Information Security', 'Blockchain', 'IoT', 'Mobile Development',
  'Swift', 'Kotlin', 'React Native', 'Flutter', 'Unity', 'Game Design', 'SAP', 'ERP',
  'Legal Research', 'Policy Analysis', 'Healthcare Management', 'Clinical Research',
  'Sustainability', 'Environmental Science', 'UX Design', 'Service Design', 'Customer Research',
]
